// <auto-generated />
using System;
using ITIDatabaseSystem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIDatabaseSystem.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260309195326_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIDatabaseSystem.Models.Course", b =>
                {
                    b.Property<int>("Crs_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crs_ID"));

                    b.Property<int?>("Crs_Duration")
                        .HasColumnType("int");

                    b.Property<string>("Crs_Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<int>("InsID")
                        .HasColumnType("int");

                    b.HasKey("Crs_ID");

                    b.HasIndex("DeptID");

                    b.HasIndex("InsID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Crs_ID = 1,
                            Crs_Duration = 40,
                            Crs_Name = "C# Programming",
                            DeptID = 1,
                            InsID = 1
                        },
                        new
                        {
                            Crs_ID = 2,
                            Crs_Duration = 35,
                            Crs_Name = "UI/UX Design",
                            DeptID = 2,
                            InsID = 2
                        },
                        new
                        {
                            Crs_ID = 3,
                            Crs_Duration = 45,
                            Crs_Name = "Mobile App Development",
                            DeptID = 3,
                            InsID = 3
                        },
                        new
                        {
                            Crs_ID = 4,
                            Crs_Duration = 50,
                            Crs_Name = "Cloud Computing",
                            DeptID = 4,
                            InsID = 4
                        },
                        new
                        {
                            Crs_ID = 5,
                            Crs_Duration = 30,
                            Crs_Name = "Open Source Software",
                            DeptID = 5,
                            InsID = 5
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.CourseSession", b =>
                {
                    b.Property<int>("CrsSession_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsSession_ID"));

                    b.Property<int>("CrsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InsID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CrsSession_ID");

                    b.HasIndex("CrsID");

                    b.HasIndex("InsID");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            CrsSession_ID = 1,
                            CrsID = 1,
                            Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 1,
                            Title = "Data Types"
                        },
                        new
                        {
                            CrsSession_ID = 2,
                            CrsID = 2,
                            Date = new DateTime(2026, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 2,
                            Title = "UI/UX Principles"
                        },
                        new
                        {
                            CrsSession_ID = 3,
                            CrsID = 3,
                            Date = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 3,
                            Title = "Mobile App Architecture"
                        },
                        new
                        {
                            CrsSession_ID = 4,
                            CrsID = 4,
                            Date = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 4,
                            Title = "Cloud Infrastructure"
                        },
                        new
                        {
                            CrsSession_ID = 5,
                            CrsID = 5,
                            Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsID = 5,
                            Title = "Open Source Contributions"
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.CourseSessionAttendance", b =>
                {
                    b.Property<int>("StdCrs_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StdCrs_ID"));

                    b.Property<int>("CrsSession_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.HasKey("StdCrs_ID");

                    b.HasIndex("CrsSession_ID");

                    b.HasIndex("StdID");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            StdCrs_ID = 1,
                            CrsSession_ID = 1,
                            Grade = 85,
                            Notes = "Good understanding of data types",
                            StdID = 1
                        },
                        new
                        {
                            StdCrs_ID = 2,
                            CrsSession_ID = 2,
                            Grade = 90,
                            Notes = "Excellent grasp of UI/UX principles",
                            StdID = 2
                        },
                        new
                        {
                            StdCrs_ID = 3,
                            CrsSession_ID = 3,
                            Grade = 80,
                            Notes = "Solid knowledge of mobile app architecture",
                            StdID = 3
                        },
                        new
                        {
                            StdCrs_ID = 4,
                            CrsSession_ID = 4,
                            Grade = 88,
                            Notes = "Strong understanding of cloud infrastructure",
                            StdID = 4
                        },
                        new
                        {
                            StdCrs_ID = 5,
                            CrsSession_ID = 5,
                            Grade = 92,
                            Notes = "Outstanding contributions to open source projects",
                            StdID = 5
                        },
                        new
                        {
                            StdCrs_ID = 6,
                            CrsSession_ID = 1,
                            Grade = 78,
                            Notes = "Needs improvement in data types",
                            StdID = 6
                        },
                        new
                        {
                            StdCrs_ID = 7,
                            CrsSession_ID = 2,
                            Grade = 82,
                            Notes = "Good understanding of UI/UX principles",
                            StdID = 7
                        },
                        new
                        {
                            StdCrs_ID = 8,
                            CrsSession_ID = 3,
                            Grade = 75,
                            Notes = "Average knowledge of mobile app architecture",
                            StdID = 8
                        },
                        new
                        {
                            StdCrs_ID = 9,
                            CrsSession_ID = 4,
                            Grade = 80,
                            Notes = "Solid understanding of cloud infrastructure",
                            StdID = 9
                        },
                        new
                        {
                            StdCrs_ID = 10,
                            CrsSession_ID = 5,
                            Grade = 85,
                            Notes = "Good contributions to open source projects",
                            StdID = 10
                        },
                        new
                        {
                            StdCrs_ID = 11,
                            CrsSession_ID = 1,
                            Grade = 82,
                            Notes = "Good understanding of data types",
                            StdID = 11
                        },
                        new
                        {
                            StdCrs_ID = 12,
                            CrsSession_ID = 2,
                            Grade = 88,
                            Notes = "Strong grasp of UI/UX principles",
                            StdID = 12
                        },
                        new
                        {
                            StdCrs_ID = 13,
                            CrsSession_ID = 3,
                            Grade = 79,
                            Notes = "Average knowledge of mobile app architecture",
                            StdID = 13
                        },
                        new
                        {
                            StdCrs_ID = 14,
                            CrsSession_ID = 4,
                            Grade = 84,
                            Notes = "Good understanding of cloud infrastructure",
                            StdID = 14
                        },
                        new
                        {
                            StdCrs_ID = 15,
                            CrsSession_ID = 5,
                            Grade = 91,
                            Notes = "Excellent contributions to open source projects",
                            StdID = 15
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Department", b =>
                {
                    b.Property<int>("Dept_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dept_ID"));

                    b.Property<string>("Dept_Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dept_Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("Dept_ID");

                    b.HasIndex("ManagerID")
                        .IsUnique()
                        .HasFilter("[ManagerID] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Dept_ID = 1,
                            Dept_Location = "Building A",
                            Dept_Name = "SD"
                        },
                        new
                        {
                            Dept_ID = 2,
                            Dept_Location = "Building B",
                            Dept_Name = "UI/UX"
                        },
                        new
                        {
                            Dept_ID = 3,
                            Dept_Location = "Building C",
                            Dept_Name = "Mobile"
                        },
                        new
                        {
                            Dept_ID = 4,
                            Dept_Location = "Building D",
                            Dept_Name = "Cloud"
                        },
                        new
                        {
                            Dept_ID = 5,
                            Dept_Location = "Building E",
                            Dept_Name = "Open Source"
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Instructor", b =>
                {
                    b.Property<int>("Ins_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ins_ID"));

                    b.Property<int?>("Dept_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ins_FName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ins_LName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ins_Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Ins_ID");

                    b.HasIndex("Dept_ID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Ins_ID = 1,
                            Dept_ID = 1,
                            Ins_FName = "Dr. Emily",
                            Ins_LName = "Smith",
                            Ins_Phone = "01020000001",
                            Salary = 5000m
                        },
                        new
                        {
                            Ins_ID = 2,
                            Dept_ID = 2,
                            Ins_FName = "Dr. Michael",
                            Ins_LName = "Johnson",
                            Ins_Phone = "01020000002",
                            Salary = 5500m
                        },
                        new
                        {
                            Ins_ID = 3,
                            Dept_ID = 3,
                            Ins_FName = "Dr. Sarah",
                            Ins_LName = "Williams",
                            Ins_Phone = "01020000003",
                            Salary = 6000m
                        },
                        new
                        {
                            Ins_ID = 4,
                            Dept_ID = 4,
                            Ins_FName = "Dr. David",
                            Ins_LName = "Brown",
                            Ins_Phone = "01020000004",
                            Salary = 6500m
                        },
                        new
                        {
                            Ins_ID = 5,
                            Dept_ID = 5,
                            Ins_FName = "Dr. Jessica",
                            Ins_LName = "Jones",
                            Ins_Phone = "01020000005",
                            Salary = 7000m
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Student", b =>
                {
                    b.Property<int>("Std_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Std_ID"));

                    b.Property<string>("Std_FName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Std_LName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Std_Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Std_ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Std_ID = 1,
                            Std_FName = "Liam",
                            Std_LName = "Anderson",
                            Std_Phone = "01010000001"
                        },
                        new
                        {
                            Std_ID = 2,
                            Std_FName = "Olivia",
                            Std_LName = "Martinez",
                            Std_Phone = "01010000002"
                        },
                        new
                        {
                            Std_ID = 3,
                            Std_FName = "Noah",
                            Std_LName = "Thompson",
                            Std_Phone = "01010000003"
                        },
                        new
                        {
                            Std_ID = 4,
                            Std_FName = "Monica",
                            Std_LName = "Williams",
                            Std_Phone = "01010000004"
                        },
                        new
                        {
                            Std_ID = 5,
                            Std_FName = "Elijah",
                            Std_LName = "Brown",
                            Std_Phone = "01010000005"
                        },
                        new
                        {
                            Std_ID = 6,
                            Std_FName = "Ava",
                            Std_LName = "Garcia",
                            Std_Phone = "01010000006"
                        },
                        new
                        {
                            Std_ID = 7,
                            Std_FName = "Lucas",
                            Std_LName = "Miller",
                            Std_Phone = "01010000007"
                        },
                        new
                        {
                            Std_ID = 8,
                            Std_FName = "Sophia",
                            Std_LName = "Davis",
                            Std_Phone = "01010000008"
                        },
                        new
                        {
                            Std_ID = 9,
                            Std_FName = "Mason",
                            Std_LName = "Wilson",
                            Std_Phone = "01010000009"
                        },
                        new
                        {
                            Std_ID = 10,
                            Std_FName = "Isabella",
                            Std_LName = "Moore",
                            Std_Phone = "01010000010"
                        },
                        new
                        {
                            Std_ID = 11,
                            Std_FName = "James",
                            Std_LName = "Taylor",
                            Std_Phone = "01010000011"
                        },
                        new
                        {
                            Std_ID = 12,
                            Std_FName = "Mia",
                            Std_LName = "Anderson",
                            Std_Phone = "01010000012"
                        },
                        new
                        {
                            Std_ID = 13,
                            Std_FName = "Benjamin",
                            Std_LName = "Thomas",
                            Std_Phone = "01010000013"
                        },
                        new
                        {
                            Std_ID = 14,
                            Std_FName = "Charlotte",
                            Std_LName = "Jackson",
                            Std_Phone = "01010000014"
                        },
                        new
                        {
                            Std_ID = 15,
                            Std_FName = "Henry",
                            Std_LName = "White",
                            Std_Phone = "01010000015"
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.StudentCourse", b =>
                {
                    b.Property<int>("StdID")
                        .HasColumnType("int");

                    b.Property<int>("CrsID")
                        .HasColumnType("int");

                    b.HasKey("StdID", "CrsID");

                    b.HasIndex("CrsID");

                    b.ToTable("StudentCourses");

                    b.HasData(
                        new
                        {
                            StdID = 1,
                            CrsID = 1
                        },
                        new
                        {
                            StdID = 2,
                            CrsID = 2
                        },
                        new
                        {
                            StdID = 3,
                            CrsID = 3
                        },
                        new
                        {
                            StdID = 4,
                            CrsID = 4
                        },
                        new
                        {
                            StdID = 5,
                            CrsID = 5
                        },
                        new
                        {
                            StdID = 6,
                            CrsID = 1
                        },
                        new
                        {
                            StdID = 7,
                            CrsID = 2
                        },
                        new
                        {
                            StdID = 8,
                            CrsID = 3
                        },
                        new
                        {
                            StdID = 9,
                            CrsID = 4
                        },
                        new
                        {
                            StdID = 10,
                            CrsID = 5
                        },
                        new
                        {
                            StdID = 11,
                            CrsID = 1
                        },
                        new
                        {
                            StdID = 12,
                            CrsID = 2
                        },
                        new
                        {
                            StdID = 13,
                            CrsID = 3
                        },
                        new
                        {
                            StdID = 14,
                            CrsID = 4
                        },
                        new
                        {
                            StdID = 15,
                            CrsID = 5
                        });
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Course", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDatabaseSystem.Models.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.CourseSession", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDatabaseSystem.Models.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InsID");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.CourseSessionAttendance", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.CourseSession", "CrsSessID")
                        .WithMany("CrsSesAttendance")
                        .HasForeignKey("CrsSession_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDatabaseSystem.Models.Student", "Student")
                        .WithMany("CrsSAs")
                        .HasForeignKey("StdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CrsSessID");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Department", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.Instructor", "InsManager")
                        .WithOne("ManagedBy")
                        .HasForeignKey("ITIDatabaseSystem.Models.Department", "ManagerID");

                    b.Navigation("InsManager");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Instructor", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("Dept_ID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.StudentCourse", b =>
                {
                    b.HasOne("ITIDatabaseSystem.Models.Course", "Course")
                        .WithMany("Std_Courses")
                        .HasForeignKey("CrsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIDatabaseSystem.Models.Student", "Student")
                        .WithMany("Std_Courses")
                        .HasForeignKey("StdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Std_Courses");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.CourseSession", b =>
                {
                    b.Navigation("CrsSesAttendance");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedBy");
                });

            modelBuilder.Entity("ITIDatabaseSystem.Models.Student", b =>
                {
                    b.Navigation("CrsSAs");

                    b.Navigation("Std_Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
